name: 'Setup Environment'
description: 'Setup common environment'
runs:
  using: 'composite'
  steps:
    - run: git config advice.detachedHead false
      shell: bash
    - name: Install mise & tools
      uses: jdx/mise-action@7a4e45a543138629540c9a1616d08632b893e492 # v5.0.1
      with:
        install: true
        env: true
        cache: true
        export_path: true
