name: 'Setup Environment'
description: 'Setup common environment'
runs:
  using: 'composite'
  steps:
    - run: git config advice.detachedHead false
      shell: bash
    - name: Install mise & tools
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      with:
        install: true
        env: true
        cache: true
        export_path: true
