logger: {
  format: Raw
  output: Stdout
  level: info
}
config: {
  node: {
    name: clouseau
    domain: clouseau.local
  }
  clouseau: {
    dir: /opt/couchdb-search/data
    commit_interval_secs: 1
  }
}
