logger: {
  format: Raw
  output: Stdout
  level: info
}
config: {
  node: {
    name: clouseau
    domain: 127.0.0.1
  }
  clouseau: {
    dir: /opt/couchdb-search/data
    commit_interval_secs: 1
  }
}
