#!/usr/bin/env bash
GIT_HOOKS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
PROJECT_DIR=${GIT_HOOKS_DIR%/*/*}
. "${PROJECT_DIR}"/scripts/console.sh

console::infoLn "\nRunning pre-commit hook ..."
console::info "(you can omit this with "
console::warn "--no-verify"
console::infoLn " but don't)"

scalafmt --reportError
formatted1=$?
ec
formatted2=$?
erlfmt --check -- \
  $(git ls-files -- "*/rebar.config" "*.app.src" "*.erl" "*.hrl" "*.escript")
formatted3=$?

console::info "* Properly formatted? * "
if [ ${formatted1} -eq 0 ] && [ ${formatted2} -eq 0 ] && [ ${formatted3} -eq 0 ]; then
  formatted=0
  echo "$(console::green)YES"
  console::infoLn "Proceeding with commit."
else
  formatted=1
  console::error "NO\n"
  console::infoLn "CANCELLING commit due to FORMATTING ERROR."
fi

exit ${formatted}
