# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Clouseau 3.x CI

on:
  push:
    branches: [ "ziose-import" ]
  pull_request:
    branches: [ "ziose-import" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ASDF_SILENT_UPGRADE: 'true'

    steps:
    - uses: actions/checkout@v4
    - name: Install asdf & tools
      uses: asdf-vm/actions/install@v3
    - name: Unit tests
      run: direnv allow . && eval "$(direnv export bash)" && make test
    - name: ZEunit tests
      run: direnv allow . && eval "$(direnv export bash)" && make zeunit
    - name: Metrics tests
      run: direnv allow . && eval "$(direnv export bash)" && make metrics-tests
    - name: CouchDB tests
      run: direnv allow . && eval "$(direnv export bash)" && make couchdb-tests
