name: Build documentation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'mise.toml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - run: git config advice.detachedHead false
      - name: Install mise & tools
        uses: jdx/mise-action@v4

      - name: Build documentation
        run: mise exec -- make docs
