# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and Erlang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Set up Erlang
      uses: gleam-lang/setup-erlang@v1.0.0
      with:
        otp-version: 22.1
    - name: Build with Maven
      run: mvn -B package --file pom.xml
